name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/veenayadav02/health-website:${{ github.run_number }}
            ghcr.io/veenayadav02/health-website:latest

      - name: Update GitOps Manifest
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          FILE_PATH=$(find . -name "frontend-rollout.yaml")

          echo "Updating file: $FILE_PATH"

          sed -i "s|image:.*|image: ghcr.io/veenayadav02/health-website:${{ github.run_number }}|g" "$FILE_PATH"

          git add "$FILE_PATH"
          git commit -m "Update image to run-${{ github.run_number }}" || echo "No changes to commit"
          git push
